CMD_HELP = '--help'
CMD_INPUT = '--input'
CMD_LEARN = '--learn'
CMD_OUTPUT = '--output'
CMD_RUN = '--run'

CONST_ALPHA = 'alpha'
CONST_MAX_ERR = 'maxError'

PARAM_ALPHA = 'a'
PARAM_FILE = 'f'
PARAM_INPUT = 'i'
PARAM_MAX_ERR = 'm'
PARAM_OUTPUT = 'o'
PARAM_ROUND = 'r'
PARAM_SAVE = 's'
PARAM_WEIGHTS = 'w'
